      - name: Install ChromeDriver
        run: |
          set -e  # Stop script on error
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f1)
          echo "Detected Chrome version: $CHROME_VERSION"

          # Fetch the exact ChromeDriver version for the detected Chrome version
          DRIVER_VERSION=$(curl -sSL "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION")

          if [ -z "$DRIVER_VERSION" ]; then
            echo "❌ Failed to fetch ChromeDriver version. Exiting."
            exit 1
          fi

          echo "Installing ChromeDriver version: $DRIVER_VERSION"
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/chromedriver/linux64/chromedriver-linux64.zip" -O chromedriver.zip

          if [ ! -f "chromedriver.zip" ]; then
            echo "❌ ChromeDriver download failed!"
            exit 1
          fi

          unzip -o chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
